Use latest snapshot for upstream
opensearch-project/geospatial pull request #12
Opened 2021-12-18 20:57 UTC by VijayanB

Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>

### Description
Update workflow and build to use 1.3.0 as upstream.
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-21 20:25 UTC, vamshin approved these changes
LGTM! Thanks

2021-12-23 20:44 UTC, dblock requested changes
CI isn't passing ;(

2021-12-24 01:41 UTC, VijayanB commented
Copied build.gradle from this PR: https://github.com/opensearch-project/opensearch-plugin-template-java/pull/16

2021-12-27 16:53 UTC, dblock approved these changes

2021-12-27 17:41 UTC, merged